CREATE TABLE "daftar_sipw" (
	"id" text PRIMARY KEY NOT NULL,
	"id_subsls" text NOT NULL,
	"idfrs" integer,
	"idsls" text,
	"kdprov" text,
	"kdkab" text,
	"kdkec" text,
	"kddesa" text,
	"kdsls" text,
	"klas" text,
	"nmprov" text,
	"nmkab" text NOT NULL,
	"nmkec" text NOT NULL,
	"nmdesa" text NOT NULL,
	"nama_sls" text NOT NULL,
	"jenis_sls" text,
	"ketua_sls" text,
	"semester_id" text,
	"semester" text,
	"j_subsls" text,
	"muatan_kk" text,
	"btt" text,
	"btt_kosong" text,
	"bku" text,
	"bbtt_non_usaha" text,
	"muatan_usaha" text,
	"muatan_total" text,
	"nama_wke" text,
	"jam_operasional" text,
	"jumlah_shift" text,
	"telepon_email" text,
	"muatan_dominan" text,
	"flag_perubahan_sls" text,
	"is_deleted" text,
	"kd_subsls" text NOT NULL,
	"created_at" timestamp NOT NULL,
	"updated_at" timestamp NOT NULL
);
